### ISSUE TITLE
Add sign out route

### ISSUE THREAD

**Issue by alereca** [team120/Universiteams#146]

**Comment by JAcciarri** [comment]
Articles/Discussions about logging out using JWT
https://stackoverflow.com/questions/43569723/jwt-authentication-how-to-implement-logout 
https://medium.com/devgorilla/how-to-log-out-when-using-jwt-a8c7823e8a6
https://softwareengineering.stackexchange.com/questions/196871/what-http-verb-should-the-route-to-log-out-of-your-web-app-be
https://www.reddit.com/r/node/comments/1bldbuu/which_http_method_do_people_use_the_most_for/
