### ISSUE TITLE
User Manual: 'Usuario Lider o Admin de Proyecto'

### ISSUE THREAD

**Issue by alereca** [team120/Universiteams#183]
https://docs.google.com/document/d/1thXBrdcxjithWOZ3PSFTAbxhOhAkRoMaab_UZC8_N3k/edit?usp=drive_link

**Comment by JAcciarri** [comment]
https://drive.google.com/drive/u/0/folders/1-9gbKGe9faUXxx2DJ_qZrMK0gNFZOhrS
