### ISSUE TITLE
User Manual: 'Usuario Admin de Sistema'

### ISSUE THREAD

**Issue by alereca** [team120/Universiteams#184]
https://docs.google.com/document/d/1Juwt-9GGAj9HJkQmIAvfLG9tOKEF8BsZwXkbxywoI1o/edit?usp=sharing

**Comment by JAcciarri** [comment]
https://drive.google.com/drive/u/0/folders/1-9gbKGe9faUXxx2DJ_qZrMK0gNFZOhrS
